- name: example copying file with owner and permissions
  hosts: db1

  vars:
    repo_url: https://github.com/prachi205/python-buzz.git
    repo_remote: origin
    repo_version: master

  tasks:
  - name: git pull
    git: repo={{repo_url}} dest=/home/psoni/deploy version=master
  - name: build the image
    docker_image: >
       name=built-by-ansible
       tag=ex1
       path=/home/psoni/deploy
       state=present
  - name: run the site in a docker container
    docker:
        name: site1
        image: "built-by-ansible:ex1"
        state: reloaded
        publish_all_ports: yes